name: FTP Test

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: ./
        with:
          server: ftp.example.com
          username: test@ftp.example.com
          password: testpassword
          exclude: |
            .gitignore
            .github
            images
